Fix broken result deletion.
elovation/elovation pull request #116
Opened 2023-10-31 13:40 UTC by dishuk13

There were two issues.
1. link_to with delete doesn't work as before on Rails 7 https://stackoverflow.com/a/74412437
2. result table has dependency on team and membership tables so needs cascade delete.

2024-11-05 07:16 UTC, christoshrousis commented on config/environments/development.rb
> +  config.action_controller.forgery_protection_origin_check = false
Why do we need this?

2024-11-05 07:17 UTC, christoshrousis requested changes
Difficult to reason about this PR even wiuth the commits, can you seperate the prettier changes from the intention of this PR?

2025-05-19 01:02 UTC, christoshrousis commented
Hey @dishuk13 and @shukladivyansh  I really appreciate you contributing to this project, but you're making it more difficult to reason about what you're doing. 

i.e. can you split this PR into one for formatting, and one for the changes you want to make. It's too difficult to read as it is right now.

2025-05-19 02:07 UTC, dishuk13 commented
My bad. 

This is a very old PR which I created. And accidentally I've been pushing to the same branch for developing other things.

Just closing it for now.

2025-05-19 02:07 UTC, closed without merging

2025-05-19 03:59 UTC, christoshrousis commented
Thank again :)